# Generated by Django 5.2.4 on 2025-07-28 03:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('sector', models.CharField(max_length=150)),
                ('market_cap', models.DecimalField(decimal_places=5, max_digits=25, null=True)),
                ('eps', models.CharField(max_length=30, null=True)),
                ('pe_ratio', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('dividend', models.CharField(max_length=20, null=True)),
                ('bvps', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('paid_capital', models.DecimalField(decimal_places=5, max_digits=50, null=True)),
                ('listed_share', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('year_yield', models.IntegerField(null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockTechnicalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('high_price_52_week', models.DecimalField(decimal_places=4, max_digits=10)),
                ('low_price_52_week', models.DecimalField(decimal_places=4, max_digits=10)),
                ('volume', models.BigIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('sentiment_score', models.IntegerField(help_text='Sentiment score ranging from -1 to 1', null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Stock', to='Stocks.stock')),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='Stocks_stoc_date_e7ea92_idx')],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
