# Generated by Django 5.2.4 on 2025-07-28 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0002_userstocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstocks',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stocks', to='Stocks.stock'),
        ),
    ]
