# Generated by Django 5.2.4 on 2025-08-09 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0004_userportfoliovalue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userportfoliovalue',
            old_name='date',
            new_name='portfolio_value_date',
        ),
    ]
