# Generated by Django 5.2.4 on 2025-10-10 02:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0006_alter_userportfoliovalue_user_userwatchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prediction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicted_stock_price', to='Stocks.stock')),
            ],
            options={
                'indexes': [models.Index(fields=['stock', 'prediction_date'], name='Stocks_stoc_stock_i_13c884_idx')],
                'unique_together': {('stock', 'prediction_date')},
            },
        ),
    ]
