# Generated by Django 5.2.4 on 2025-10-29 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0007_stockprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPredictionPending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField()),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stocks.stock')),
            ],
            options={
                'unique_together': {('stock', 'prediction_date')},
            },
        ),
    ]
