# Generated by Django 5.2.4 on 2025-10-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0009_alter_stockprediction_prediction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprediction',
            name='predicted_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
